import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body <body className="bg-black text-white">
  <header className="border-b border-zinc-900">
    <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
      
      <div className="font-black uppercase tracking-widest">
        A CALIBRATIONS
      </div>

      <nav className="flex gap-6 text-sm uppercase text-zinc-400">
        <a href="#services" className="hover:text-white">Services</a>
        <a href="#" className="hover:text-white">Platforms</a>
        <a href="#" className="hover:text-white">Contact</a>
      </nav>

    </div>
  </header>

  {children}

  <footer className="border-t border-zinc-900 px-6 py-10 text-sm text-zinc-500">
    <div className="mx-auto max-w-6xl">
      © {new Date().getFullYear()} A Calibrations
    </div>
  </footer>
</body></body>
    </html>
  );
}
